### PR TITLE
Uni lib

### PR DESCRIPTION
**Pull request by brucerennie**
Updates have been made to uni/lib/langprocs.icn to use the Unicon functions fieldnames(r), serial(o), membernames(o) and methodnames(o) to remove implementation dependencies within the langprocs procedures.

Two of the langproc procedures get_class_name(o) and get_id(o) have been marked deprecated as get_class_name is a direct match for classname() and get_id is a direct match for serial().

### CODE REVIEW

**Comment by brucerennie** [comment]
I should note that I have been in communication with Steve Wampler and it was his suggestion to mark the two procedures get_id() and get_class_name() as deprecated.

**Review by StephenWampler — APPROVED** [review]
These changes look fine to me.

**Review by StephenWampler — COMMENTED** [review]
I think get_class_for_name(name) still has a use.  Check $UNICON/uni/gui/migration.icn.

**Comment by Jafaral** [comment]
Hi @brucerennie, I do see that you are keeping the PR up to date with the master branch which is good. Can you please do that using a rebase instead of a merge ? that way you don't introduce  merge commits like  the three commits yo have on top of this PR. With rebase, all of the updates from the master branch slide beneath your changes without introducing new commits.

**Comment by brucerennie** [comment]
Good evening Jafar,
Is this what you meant.

**Comment by Jafaral** [comment]
Hi Bruce,  yes, perfect.  Notice that in some cases where there are a lot of merge conflicts and a long series of commits in a PR, it might be hard to update via rebase. In such cases regular merge is ok. So rebase is preferred  unless it is hard to do.

**Comment by brucerennie** [comment]
At this point, these are the relevant commits that I am proposing for the uni/lib files. I have used this branch as my current test system on my local machine and at this point I have not come across any problems as such.

**Comment by Jafaral** [comment]
Thanks for the good work @brucerennie, I will review this PR and let you know. @Don-Ward  and @StephenWampler might also have things to say.

**Comment by brucerennie** [comment]
The more the merrier to look at the changes. There are some further changes that I think could be done. But that is for a later time. Thanks for your help at getting the various git quirks sorted.

**Comment by Jafaral** [comment]
@brucerennie , I have been busy trying to get release 13.2 out of the door. Will come back to this in a day or two  and be ready to merge.
Thanks.

**Comment by brucerennie** [comment]
Thanks Jafar. Let me know if anything else needs to be done.

**Pull request merged**
